;БЛОК 2: ESP8266 (Семейство Xtensa LX106)
; ==========================================
; 5. NodeMCU v1.0 (ESP-12E)
; ==========================================
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM5
upload_speed = 921600                      ; Для быстрой заливки
monitor_speed = 115200

; ==========================================
; 6. Wemos D1 Mini (клон NodeMCU, но компактный)
; ==========================================
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_port = COM5
upload_speed = 921600
monitor_speed = 115200