;БЛОК 4: AVR (Arduino UNO / Nano / Mega)
; ==========================================
; 10. Arduino UNO (автопоиск порта)
; ==========================================
[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM5
monitor_speed = 9600                    

; ==========================================
; 11. Arduino Nano (атмега328P, старый бутлоадер или новый)
; ==========================================
[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = COM5
upload_protocol = arduino
monitor_speed = 9600

; ==========================================
; 12. Arduino Mega 2560
; ==========================================
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM5
monitor_speed = 115200                    ; У Меги часто ставят 115200